import argparse
import os

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.widgets import Button
import numpy as np
from scipy.io import loadmat


# 100% GENERATED BY AI


SEGMENT_KEYS = ("pre_segments", "dur_segments")


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Plot segments from .mat files produced by prep.py with interactive navigation."
        )
    )
    parser.add_argument("file", help="Path to .mat file generated by prep.py")
    parser.add_argument(
        "--segment-type",
        choices=("pre", "dur"),
        default="pre",
        help="Segment set to plot: pre (pre_segments) or dur (dur_segments).",
    )
    parser.add_argument(
        "--index",
        type=int,
        default=0,
        help="Zero-based segment index within the selected segment set.",
    )
    return parser.parse_args()


def _to_1d_float_segment(obj):
    """Convert loaded MATLAB cell content to a flat float numpy array."""
    arr = np.asarray(obj)
    arr = np.squeeze(arr)
    return np.asarray(arr, dtype=float).ravel()


def load_segments(mat_path, segment_type):
    data = loadmat(mat_path)

    key = "pre_segments" if segment_type == "pre" else "dur_segments"
    if key not in data:
        raise KeyError(
            f"'{key}' not found in '{mat_path}'. Expected keys: {', '.join(SEGMENT_KEYS)}"
        )

    cell = np.asarray(data[key], dtype=object)
    if cell.size == 0:
        return []

    # MATLAB cell arrays are commonly Nx1, 1xN, or object arrays after scipy loading.
    flat_cells = cell.ravel()
    segments = [_to_1d_float_segment(seg) for seg in flat_cells]
    return segments


def load_file_bundle(mat_path):
    return {
        "path": mat_path,
        "name": os.path.basename(mat_path),
        "pre_segments": load_segments(mat_path, "pre"),
        "dur_segments": load_segments(mat_path, "dur"),
    }


def build_file_list(start_file):
    folder = os.path.dirname(os.path.abspath(start_file))
    bundles = []

    for name in sorted(os.listdir(folder)):
        if not name.lower().endswith(".mat"):
            continue

        path = os.path.join(folder, name)
        try:
            bundle = load_file_bundle(path)
        except Exception:
            continue

        if len(bundle["pre_segments"]) == 0 and len(bundle["dur_segments"]) == 0:
            continue

        bundles.append(bundle)

    return bundles


def get_sampling_rate(data):
    fs = data.get("fs", None)
    if fs is None:
        return None
    fs_arr = np.asarray(fs).squeeze()
    if fs_arr.size == 0:
        return None
    return float(fs_arr)


def segment_label(segment_type, index):
    return f"{segment_type}_segments[{index}]"


def combined_segment_entries(bundle):
    entries = []
    for segment_type in ("pre", "dur"):
        for index, segment in enumerate(bundle[f"{segment_type}_segments"]):
            entries.append((segment_type, index, segment))
    return entries


def build_view(bundle, segment_type, index):
    segments = bundle[f"{segment_type}_segments"]
    if index < 0 or index >= len(segments):
        raise IndexError(
            f"Segment index {index} out of range for {segment_type}_segments in {bundle['name']}"
        )

    segment = segments[index]
    n = len(segment)
    if n == 0:
        raise ValueError(f"Selected segment is empty in {bundle['name']}")

    mat_data = loadmat(bundle["path"])
    fs = get_sampling_rate(mat_data)

    if fs is not None and fs > 0:
        x = np.arange(n) / fs
        x_label = "Time (s)"
    else:
        x = np.arange(n)
        x_label = "Sample"

    y_min, y_max = float(np.min(segment)), float(np.max(segment))
    if np.isclose(y_min, y_max):
        y_pad = 1.0 if np.isclose(y_min, 0.0) else abs(y_min) * 0.1
    else:
        y_pad = (y_max - y_min) * 0.05

    return {
        "x": x,
        "x_label": x_label,
        "segment": segment,
        "n": n,
        "x_full_min": float(x[0]),
        "x_full_max": float(x[-1]) if n > 1 else float(x[0] + 1.0),
        "y_full_min": y_min - y_pad,
        "y_full_max": y_max + y_pad,
    }


def main():
    args = parse_args()

    if not os.path.exists(args.file):
        raise FileNotFoundError(f"Input file does not exist: {args.file}")

    bundles = build_file_list(args.file)
    if len(bundles) == 0:
        raise ValueError("No MAT files with segments were found in the input folder.")

    current_file_index = -1
    for file_index, bundle in enumerate(bundles):
        if os.path.abspath(bundle["path"]) == os.path.abspath(args.file):
            current_file_index = file_index
            break

    if current_file_index < 0:
        raise ValueError(f"Input file not found in navigable MAT list: {args.file}")

    current_segment_type = args.segment_type
    current_segment_index = args.index

    current_bundle = bundles[current_file_index]
    current_segments = current_bundle[f"{current_segment_type}_segments"]
    if len(current_segments) == 0:
        raise ValueError(
            f"No segments found in '{current_segment_type}_segments' for file: {args.file}"
        )
    if current_segment_index < 0 or current_segment_index >= len(current_segments):
        raise IndexError(
            f"Segment index {current_segment_index} out of range for '{current_segment_type}_segments' "
            f"(valid range: 0 to {len(current_segments) - 1})."
        )

    view = build_view(current_bundle, current_segment_type, current_segment_index)

    fig = plt.figure(figsize=(12, 5))
    ax = fig.add_axes((0.12, 0.40, 0.76, 0.52))

    line, = ax.plot(view["x"], view["segment"], linewidth=1.0)
    ax.set_title(
        f"{current_bundle['name']} | {segment_label(current_segment_type, current_segment_index)} | n={view['n']}"
    )
    ax.set_xlabel(view["x_label"])
    ax.set_ylabel("Respiratory Signal")
    ax.grid(True, alpha=0.3)

    overview_ax = fig.add_axes((0.12, 0.14, 0.76, 0.10))
    overview_line, = overview_ax.plot(view["x"], view["segment"], linewidth=0.8, color="0.45")
    overview_ax.set_xlim(view["x_full_min"], view["x_full_max"])
    overview_ax.set_ylim(view["y_full_min"], view["y_full_max"])
    overview_ax.set_yticks([])
    overview_ax.set_xlabel("Signal overview")
    overview_ax.set_facecolor("#f7f7f7")
    overview_ax.grid(True, axis="x", alpha=0.15)
    overview_ax.set_navigate(False)

    viewport_state = {
        "updating": False,
        "dragging": False,
        "drag_offset": 0.0,
        "window_width": view["x_full_max"] - view["x_full_min"],
    }

    viewport = Rectangle(
        (view["x_full_min"], view["y_full_min"]),
        viewport_state["window_width"],
        view["y_full_max"] - view["y_full_min"],
        facecolor=(0.2, 0.4, 0.9, 0.15),
        edgecolor=(0.2, 0.4, 0.9, 0.9),
        linewidth=1.6,
    )
    overview_ax.add_patch(viewport)

    def update_viewport(left_edge, right_edge):
        left_edge = float(left_edge)
        right_edge = float(right_edge)
        if right_edge < left_edge:
            left_edge, right_edge = right_edge, left_edge

        full_left = view["x_full_min"]
        full_right = view["x_full_max"]
        left_edge = max(full_left, left_edge)
        right_edge = min(full_right, right_edge)

        viewport_state["window_width"] = max(right_edge - left_edge, 0.0)
        viewport.set_x(left_edge)
        viewport.set_width(viewport_state["window_width"])
        viewport.set_y(view["y_full_min"])
        viewport.set_height(view["y_full_max"] - view["y_full_min"])

    def set_visible_window(left_edge):
        full_left = view["x_full_min"]
        full_right = view["x_full_max"]
        window_width = viewport_state["window_width"]

        if np.isclose(window_width, 0.0) or np.isclose(window_width, full_right - full_left):
            ax.set_xlim(full_left, full_right)
            return

        max_left = max(full_left, full_right - window_width)
        clamped_left = min(max(float(left_edge), full_left), max_left)
        ax.set_xlim(clamped_left, clamped_left + window_width)

    def on_xlim_changed(_axes):
        if viewport_state["updating"]:
            return

        current_left, current_right = ax.get_xlim()
        full_left = view["x_full_min"]
        full_right = view["x_full_max"]

        if current_right <= current_left:
            return

        viewport_state["updating"] = True
        try:
            update_viewport(current_left, current_right)
            fig.canvas.draw_idle()
        finally:
            viewport_state["updating"] = False

    def update_plot():
        nonlocal view
        current_bundle = bundles[current_file_index]
        view = build_view(current_bundle, current_segment_type, current_segment_index)
        line.set_data(view["x"], view["segment"])
        overview_line.set_data(view["x"], view["segment"])
        ax.set_title(
            f"{current_bundle['name']} | {segment_label(current_segment_type, current_segment_index)} | n={view['n']}"
        )
        ax.set_xlabel(view["x_label"])
        ax.set_xlim(view["x_full_min"], view["x_full_max"])
        ax.set_ylim(view["y_full_min"], view["y_full_max"])
        overview_ax.set_xlim(view["x_full_min"], view["x_full_max"])
        overview_ax.set_ylim(view["y_full_min"], view["y_full_max"])
        update_viewport(view["x_full_min"], view["x_full_max"])
        viewport_state["window_width"] = view["x_full_max"] - view["x_full_min"]
        fig.canvas.draw_idle()

    def on_press(event):
        if event.inaxes != overview_ax or event.xdata is None:
            return

        contains, _ = viewport.contains(event)
        if not contains:
            return

        viewport_state["dragging"] = True
        viewport_state["drag_offset"] = float(event.xdata) - float(viewport.get_x())

    def on_motion(event):
        if not viewport_state["dragging"] or event.inaxes != overview_ax or event.xdata is None:
            return

        full_left = view["x_full_min"]
        full_right = view["x_full_max"]
        window_width = viewport_state["window_width"]

        if np.isclose(window_width, 0.0) or np.isclose(window_width, full_right - full_left):
            return

        left_edge = float(event.xdata) - viewport_state["drag_offset"]
        max_left = max(full_left, full_right - window_width)
        clamped_left = min(max(left_edge, full_left), max_left)

        viewport_state["updating"] = True
        try:
            set_visible_window(clamped_left)
            update_viewport(clamped_left, clamped_left + window_width)
        finally:
            viewport_state["updating"] = False
        fig.canvas.draw_idle()

    def on_release(_event):
        viewport_state["dragging"] = False

    def move_next(_event):
        nonlocal current_file_index, current_segment_type, current_segment_index

        current_bundle = bundles[current_file_index]
        current_entries = combined_segment_entries(current_bundle)
        current_position = None
        for position, (segment_type, index, _segment) in enumerate(current_entries):
            if segment_type == current_segment_type and index == current_segment_index:
                current_position = position
                break

        if current_position is None:
            return

        if current_position + 1 < len(current_entries):
            current_segment_type, current_segment_index, _segment = current_entries[current_position + 1]
            update_plot()
            return

        if current_file_index + 1 >= len(bundles):
            return

        next_file_index = current_file_index + 1
        next_bundle = bundles[next_file_index]
        next_entries = combined_segment_entries(next_bundle)
        if len(next_entries) == 0:
            return

        current_file_index = next_file_index
        current_segment_type, current_segment_index, _segment = next_entries[0]
        update_plot()

    def move_back(_event):
        nonlocal current_file_index, current_segment_type, current_segment_index

        current_bundle = bundles[current_file_index]
        current_entries = combined_segment_entries(current_bundle)
        current_position = None
        for position, (segment_type, index, _segment) in enumerate(current_entries):
            if segment_type == current_segment_type and index == current_segment_index:
                current_position = position
                break

        if current_position is None:
            return

        if current_position > 0:
            current_segment_type, current_segment_index, _segment = current_entries[current_position - 1]
            update_plot()
            return

        if current_file_index == 0:
            return

        prev_file_index = current_file_index - 1
        prev_bundle = bundles[prev_file_index]
        prev_entries = combined_segment_entries(prev_bundle)
        if len(prev_entries) == 0:
            return

        current_file_index = prev_file_index
        current_segment_type, current_segment_index, _segment = prev_entries[-1]
        update_plot()

    ax.callbacks.connect("xlim_changed", on_xlim_changed)
    fig.canvas.mpl_connect("button_press_event", on_press)
    fig.canvas.mpl_connect("motion_notify_event", on_motion)
    fig.canvas.mpl_connect("button_release_event", on_release)

    update_plot()

    back_ax = fig.add_axes((0.74, 0.04, 0.1, 0.05))
    back_btn = Button(back_ax, "Back")
    next_ax = fig.add_axes((0.86, 0.04, 0.1, 0.05))
    next_btn = Button(next_ax, "Next")

    back_btn.on_clicked(move_back)
    next_btn.on_clicked(move_next)

    plt.show()


if __name__ == "__main__":
    main()
