import argparse
import os
from typing import cast, Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.widgets import Button, CheckButtons
import numpy as np
from scipy.io import loadmat


EPOCH_KEYS = ("pre_epochs", "dur_epochs")


Bundle = Dict[str, object]


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Plot epochs from .mat files produced by epochize.py with interactive navigation."
        )
    )
    parser.add_argument("file", help="Path to .mat file generated by epochize.py")
    parser.add_argument(
        "--epoch-type",
        choices=("pre", "dur"),
        default="pre",
        help="Epoch set to plot: pre (pre_epochs) or dur (dur_epochs).",
    )
    parser.add_argument(
        "--index",
        type=int,
        default=0,
        help="Zero-based epoch index within the selected epoch set.",
    )
    parser.add_argument(
        "--fixed-y",
        action="store_true",
        default=False,
        help="Start with fixed symmetric Y-axis across epochs for the file.",
    )
    return parser.parse_args()


def _to_1d_float_epoch(obj):
    """Convert loaded MATLAB epoch content to a flat float numpy array."""
    arr = np.asarray(obj)
    arr = np.squeeze(arr)
    return np.asarray(arr, dtype=float).ravel()


def get_sampling_rate(data):
    fs = data.get("fs", None)
    if fs is None:
        return None
    fs_arr = np.asarray(fs).squeeze()
    if fs_arr.size == 0:
        return None
    return float(fs_arr)


def get_epoch_length_sec(data):
    value = data.get("epoch_length_sec", None)
    if value is None:
        return None
    value_arr = np.asarray(value).squeeze()
    if value_arr.size == 0:
        return None
    return float(value_arr)


def load_epochs_from_data(data, epoch_type):
    key = "pre_epochs" if epoch_type == "pre" else "dur_epochs"
    if key not in data:
        raise KeyError(f"'{key}' not found. Expected keys: {', '.join(EPOCH_KEYS)}")
    # Handle either numeric 2D arrays (n_epochs x epoch_len) or cell arrays (object arrays)
    raw = data[key]
    raw_arr = np.asarray(raw)

    # Empty
    if raw_arr.size == 0:
        return []

    # Numeric 2D array: each row is an epoch
    if isinstance(raw_arr, np.ndarray) and raw_arr.dtype != object and raw_arr.ndim == 2:
        return [np.asarray(raw_arr[i, :], dtype=float).ravel() for i in range(raw_arr.shape[0])]

    # Otherwise assume object/cell array
    flat_values = np.asarray(raw, dtype=object).reshape(-1)
    return [_to_1d_float_epoch(epoch) for epoch in flat_values]


def load_file_bundle(mat_path):
    data = loadmat(mat_path)
    return {
        "path": mat_path,
        "name": os.path.basename(mat_path),
        "fs": get_sampling_rate(data),
        "epoch_length_sec": get_epoch_length_sec(data),
        "pre_epochs": load_epochs_from_data(data, "pre"),
        "dur_epochs": load_epochs_from_data(data, "dur"),
    }


def build_file_list(start_file):
    folder = os.path.dirname(os.path.abspath(start_file))
    return [
        os.path.join(folder, name)
        for name in sorted(os.listdir(folder))
        if name.lower().endswith(".mat")
    ]


def epoch_label(epoch_type, index):
    return f"{epoch_type}_epochs[{index}]"


def combined_epoch_entries(bundle):
    entries = []
    for epoch_type in ("pre", "dur"):
        for index, epoch in enumerate(bundle[f"{epoch_type}_epochs"]):
            entries.append((epoch_type, index, epoch))
    return entries


def build_view(bundle, epoch_type, index):
    epochs = bundle[f"{epoch_type}_epochs"]
    if index < 0 or index >= len(epochs):
        raise IndexError(
            f"Epoch index {index} out of range for {epoch_type}_epochs in {bundle['name']}"
        )

    epoch = epochs[index]
    n = len(epoch)
    if n == 0:
        raise ValueError(f"Selected epoch is empty in {bundle['name']}")

    fs = bundle.get("fs")
    if fs is not None and fs > 0:
        x = np.arange(n) / fs
        x_label = "Time (s)"
    else:
        x = np.arange(n)
        x_label = "Sample"

    y_min, y_max = float(np.min(epoch)), float(np.max(epoch))
    if np.isclose(y_min, y_max):
        y_pad = 1.0 if np.isclose(y_min, 0.0) else abs(y_min) * 0.1
    else:
        y_pad = (y_max - y_min) * 0.05

    return {
        "x": x,
        "x_label": x_label,
        "epoch": epoch,
        "n": n,
        "x_full_min": float(x[0]),
        "x_full_max": float(x[-1]) if n > 1 else float(x[0] + 1.0),
        "y_full_min": y_min - y_pad,
        "y_full_max": y_max + y_pad,
    }


def load_bundle_for_path(bundle_cache, path):
    if path not in bundle_cache:
        bundle_cache[path] = load_file_bundle(path)
    return bundle_cache[path]


def compute_bundle_fixed_y(bundle) -> Optional[float]:
    """Compute symmetric Y limit for a bundle across all epochs in the file.

    Returns the positive Y (so limits are [-Y, Y]) or None if no numeric data.
    """
    max_vals = []
    for key in ("pre_epochs", "dur_epochs"):
        for epoch in bundle.get(key, []) or []:
            try:
                arr = np.asarray(epoch, dtype=float)
            except Exception:
                continue
            if arr.size == 0:
                continue
            max_vals.append(float(np.max(np.abs(arr))))

    if not max_vals:
        return None
    y = float(max(max_vals))
    if np.isclose(y, 0.0):
        return 1.0
    return y


def next_valid_bundle(file_paths, start_index, bundle_cache, direction):
    step = 1 if direction > 0 else -1
    index = start_index + step
    while 0 <= index < len(file_paths):
        try:
            bundle = load_bundle_for_path(bundle_cache, file_paths[index])
        except Exception:
            index += step
            continue
        if len(bundle["pre_epochs"]) > 0 or len(bundle["dur_epochs"]) > 0:
            return index, bundle
        index += step
    return None, None


def main():
    args = parse_args()

    if not os.path.exists(args.file):
        raise FileNotFoundError(f"Input file does not exist: {args.file}")

    file_paths = build_file_list(args.file)
    if len(file_paths) == 0:
        raise ValueError("No MAT files were found in the input folder.")

    current_file_index: int = -1
    for file_index, path in enumerate(file_paths):
        if os.path.abspath(path) == os.path.abspath(args.file):
            current_file_index = file_index
            break

    if current_file_index < 0:
        raise ValueError(f"Input file not found in MAT list: {args.file}")

    bundle_cache: Dict[str, Bundle] = {}
    current_bundle = load_bundle_for_path(bundle_cache, file_paths[current_file_index])
    current_epoch_type = args.epoch_type
    current_epoch_index = args.index
    fixed_y_enabled = bool(args.fixed_y)
    bundle_fixed_y = compute_bundle_fixed_y(current_bundle)

    current_epochs = cast(List[np.ndarray], current_bundle[f"{current_epoch_type}_epochs"])
    if len(current_epochs) == 0:
        raise ValueError(
            f"No epochs found in '{current_epoch_type}_epochs' for file: {args.file}"
        )
    if current_epoch_index < 0 or current_epoch_index >= len(current_epochs):
        raise IndexError(
            f"Epoch index {current_epoch_index} out of range for '{current_epoch_type}_epochs' "
            f"(valid range: 0 to {len(current_epochs) - 1})."
        )

    view = build_view(current_bundle, current_epoch_type, current_epoch_index)

    fig = plt.figure(figsize=(12, 5))
    ax = fig.add_axes((0.12, 0.40, 0.76, 0.52))

    line, = ax.plot(view["x"], view["epoch"], linewidth=1.0)
    ax.set_title(
        f"{current_bundle['name']} | {epoch_label(current_epoch_type, current_epoch_index)} | n={view['n']}"
    )
    ax.set_xlabel(view["x_label"])
    ax.set_ylabel("Amplitude")
    ax.grid(True, alpha=0.3)
    # Apply fixed Y if requested and available
    if fixed_y_enabled and bundle_fixed_y is not None:
        ax.set_ylim(-bundle_fixed_y, bundle_fixed_y)

    overview_ax = fig.add_axes((0.12, 0.14, 0.76, 0.10))
    overview_line, = overview_ax.plot(view["x"], view["epoch"], linewidth=0.8, color="0.45")
    overview_ax.set_xlim(view["x_full_min"], view["x_full_max"])
    overview_ax.set_ylim(view["y_full_min"], view["y_full_max"])
    overview_ax.set_yticks([])
    overview_ax.set_xlabel("Epoch overview")
    overview_ax.set_facecolor("#f7f7f7")
    overview_ax.grid(True, axis="x", alpha=0.15)
    overview_ax.set_navigate(False)

    viewport_state = {
        "updating": False,
        "dragging": False,
        "drag_offset": 0.0,
        "window_width": view["x_full_max"] - view["x_full_min"],
    }

    viewport = Rectangle(
        (view["x_full_min"], view["y_full_min"]),
        viewport_state["window_width"],
        view["y_full_max"] - view["y_full_min"],
        facecolor=(0.2, 0.4, 0.9, 0.15),
        edgecolor=(0.2, 0.4, 0.9, 0.9),
        linewidth=1.6,
    )
    overview_ax.add_patch(viewport)

    def update_viewport(left_edge, right_edge):
        left_edge = float(left_edge)
        right_edge = float(right_edge)
        if right_edge < left_edge:
            left_edge, right_edge = right_edge, left_edge

        full_left = view["x_full_min"]
        full_right = view["x_full_max"]
        left_edge = max(full_left, left_edge)
        right_edge = min(full_right, right_edge)

        viewport_state["window_width"] = max(right_edge - left_edge, 0.0)
        viewport.set_x(left_edge)
        viewport.set_width(viewport_state["window_width"])
        viewport.set_y(view["y_full_min"])
        viewport.set_height(view["y_full_max"] - view["y_full_min"])

    def set_visible_window(left_edge):
        full_left = view["x_full_min"]
        full_right = view["x_full_max"]
        window_width = viewport_state["window_width"]

        if np.isclose(window_width, 0.0) or np.isclose(window_width, full_right - full_left):
            ax.set_xlim(full_left, full_right)
            return

        max_left = max(full_left, full_right - window_width)
        clamped_left = min(max(float(left_edge), full_left), max_left)
        ax.set_xlim(clamped_left, clamped_left + window_width)

    def on_xlim_changed(_axes):
        if viewport_state["updating"]:
            return

        current_left, current_right = ax.get_xlim()
        if current_right <= current_left:
            return

        viewport_state["updating"] = True
        try:
            update_viewport(current_left, current_right)
            fig.canvas.draw_idle()
        finally:
            viewport_state["updating"] = False

    def update_plot():
        nonlocal view
        nonlocal bundle_fixed_y
        current_bundle = load_bundle_for_path(bundle_cache, file_paths[current_file_index])
        bundle_fixed_y = compute_bundle_fixed_y(current_bundle)
        view = build_view(current_bundle, current_epoch_type, current_epoch_index)
        line.set_data(view["x"], view["epoch"])
        overview_line.set_data(view["x"], view["epoch"])
        ax.set_title(
            f"{current_bundle['name']} | {epoch_label(current_epoch_type, current_epoch_index)} | n={view['n']}"
        )
        ax.set_xlabel(view["x_label"])
        ax.set_xlim(view["x_full_min"], view["x_full_max"])
        # Respect fixed Y setting if enabled
        if fixed_y_enabled and bundle_fixed_y is not None:
            ax.set_ylim(-bundle_fixed_y, bundle_fixed_y)
        else:
            ax.set_ylim(view["y_full_min"], view["y_full_max"])
        overview_ax.set_xlim(view["x_full_min"], view["x_full_max"])
        overview_ax.set_ylim(view["y_full_min"], view["y_full_max"])
        update_viewport(view["x_full_min"], view["x_full_max"])
        viewport_state["window_width"] = view["x_full_max"] - view["x_full_min"]
        fig.canvas.draw_idle()

    def on_press(event):
        if event.inaxes != overview_ax or event.xdata is None:
            return

        contains, _ = viewport.contains(event)
        if not contains:
            return

        viewport_state["dragging"] = True
        viewport_state["drag_offset"] = float(event.xdata) - float(viewport.get_x())

    def on_motion(event):
        if not viewport_state["dragging"] or event.inaxes != overview_ax or event.xdata is None:
            return

        full_left = view["x_full_min"]
        full_right = view["x_full_max"]
        window_width = viewport_state["window_width"]

        if np.isclose(window_width, 0.0) or np.isclose(window_width, full_right - full_left):
            return

        left_edge = float(event.xdata) - viewport_state["drag_offset"]
        max_left = max(full_left, full_right - window_width)
        clamped_left = min(max(left_edge, full_left), max_left)

        viewport_state["updating"] = True
        try:
            set_visible_window(clamped_left)
            update_viewport(clamped_left, clamped_left + window_width)
        finally:
            viewport_state["updating"] = False
        fig.canvas.draw_idle()

    def on_release(_event):
        viewport_state["dragging"] = False

    def move_next(_event):
        nonlocal current_file_index, current_epoch_type, current_epoch_index

        current_bundle = load_bundle_for_path(bundle_cache, file_paths[current_file_index])
        current_entries = combined_epoch_entries(current_bundle)
        current_position = None
        for position, (epoch_type, index, _epoch) in enumerate(current_entries):
            if epoch_type == current_epoch_type and index == current_epoch_index:
                current_position = position
                break

        if current_position is None:
            return

        if current_position + 1 < len(current_entries):
            current_epoch_type, current_epoch_index, _epoch = current_entries[current_position + 1]
            update_plot()
            return

        next_index, next_bundle = next_valid_bundle(file_paths, current_file_index, bundle_cache, 1)
        if next_index is None or next_bundle is None:
            return

        current_file_index = next_index
        current_epoch_type = "pre" if len(next_bundle["pre_epochs"]) > 0 else "dur"
        current_epoch_index = 0
        update_plot()

    def move_back(_event):
        nonlocal current_file_index, current_epoch_type, current_epoch_index

        current_bundle = load_bundle_for_path(bundle_cache, file_paths[current_file_index])
        current_entries = combined_epoch_entries(current_bundle)
        current_position = None
        for position, (epoch_type, index, _epoch) in enumerate(current_entries):
            if epoch_type == current_epoch_type and index == current_epoch_index:
                current_position = position
                break

        if current_position is None:
            return

        if current_position > 0:
            current_epoch_type, current_epoch_index, _epoch = current_entries[current_position - 1]
            update_plot()
            return

        prev_index, prev_bundle = next_valid_bundle(file_paths, current_file_index, bundle_cache, -1)
        if prev_index is None or prev_bundle is None:
            return

        current_file_index = prev_index
        if len(prev_bundle["dur_epochs"]) > 0:
            current_epoch_type = "dur"
            current_epoch_index = len(prev_bundle["dur_epochs"]) - 1
        else:
            current_epoch_type = "pre"
            current_epoch_index = len(prev_bundle["pre_epochs"]) - 1
        update_plot()

    ax.callbacks.connect("xlim_changed", on_xlim_changed)
    fig.canvas.mpl_connect("button_press_event", on_press)
    fig.canvas.mpl_connect("motion_notify_event", on_motion)
    fig.canvas.mpl_connect("button_release_event", on_release)

    update_plot()

    cb_ax = fig.add_axes((0.02, 0.04, 0.12, 0.08))
    cb = CheckButtons(cb_ax, ["Fixed Y"], [fixed_y_enabled])
    cb_ax.set_title("Options", fontsize=8)

    def on_fixed_y(label):
        nonlocal fixed_y_enabled, bundle_fixed_y, view
        fixed_y_enabled = bool(cb.get_status()[0])
        if fixed_y_enabled and bundle_fixed_y is not None:
            ax.set_ylim(-bundle_fixed_y, bundle_fixed_y)
        else:
            ax.set_ylim(view["y_full_min"], view["y_full_max"])
        fig.canvas.draw_idle()

    cb.on_clicked(on_fixed_y)

    back_ax = fig.add_axes((0.74, 0.04, 0.1, 0.05))
    back_btn = Button(back_ax, "Back")
    next_ax = fig.add_axes((0.86, 0.04, 0.1, 0.05))
    next_btn = Button(next_ax, "Next")

    back_btn.on_clicked(move_back)
    next_btn.on_clicked(move_next)

    plt.show()


if __name__ == "__main__":
    main()

